name: Trigger auto deployment for nodejs-fruits-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/nodejs-fruits-api-AutoDeployTrigger-93380db5-41d3-47d4-a401-a67f35d435ee.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: azureossd.azurecr.io
          username: ${{ secrets.NODEJSFRUITSAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.NODEJSFRUITSAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azureossd.azurecr.io/nodejs-fruits-api:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NODEJSFRUITSAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n nodejs-fruits-api -g edisga-resourcegroup --server azureossd.azurecr.io --username  ${{ secrets.NODEJSFRUITSAPI_REGISTRY_USERNAME }} --password ${{ secrets.NODEJSFRUITSAPI_REGISTRY_PASSWORD }}
            az containerapp update -n nodejs-fruits-api -g edisga-resourcegroup --image azureossd.azurecr.io/nodejs-fruits-api:${{ github.sha }}
